export enum AppRole {
  ADMIN_CUMBRES = 'ADMIN_CUMBRES',
  ADMIN_FINCA = 'ADMIN_FINCA',
  TECNICO = 'TECNICO',
  AGRICULTOR = 'AGRICULTOR',
  PROVEEDOR = 'PROVEEDOR',
  COMPRADOR_CERTIFICADORA = 'COMPRADOR_CERTIFICADORA',
  CLIENTE = 'CLIENTE',
  PUBLICO = 'PUBLICO',
}
